name: pronto
on: [pull_request]

jobs:
  linters:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    if: ${{ !contains(github.actor, '[bot]') }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - run: |
          git fetch --no-tags --prune --depth=10 origin +refs/heads/*:refs/remotes/origin/*
          sudo apt-get install -y cmake
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1

      - name: Install required gems for linters
        run: gem install faraday-retry rubocop-rails rubocop-rspec rubocop-performance reek haml_lint eslintrb brakeman

      - name: Install pronto runners
        run: gem install pronto pronto-rubocop pronto-reek pronto-haml pronto-eslint pronto-brakeman

      - name: Run Pronto
        run: pronto run -f github_combined_status github_pr -c origin/${{ github.base_ref }}

        env:
          PRONTO_PULL_REQUEST_ID: ${{ github.event.pull_request.number }}
          PRONTO_GITHUB_ACCESS_TOKEN: "${{ github.token }}"
