require:
  - rubocop-rails
  - rubocop-performance
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - bin/**/*
    - db/**/*
    - tmp/**/*
    - node_modules/**/*
  DisplayCopNames: true
  DisplayStyleGuide: true
  CacheRootDirectory: tmp

Metrics/MethodLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/FrozenStringLiteralComment:
  Exclude:
    - spec/**/*

RSpec/MessageSpies:
  EnforcedStyle: receive

RSpec/MultipleExpectations:
  Exclude:
    - spec/features/**/*.rb
    - spec/system/**/*.rb
    - spec/views/**/*.rb

RSpec/ExampleLength:
  CountAsOne: ['array', 'hash', 'heredoc']
  Exclude:
    - spec/features/**/*.rb
    - spec/system/**/*.rb

RSpec/DescribeClass:
  Exclude:
    - spec/views/**/*.rb
    - spec/features/**/*.rb
    - spec/system/**/*.rb

RSpec/ImplicitSubject:
  EnforcedStyle: single_statement_only

RSpec/SharedExamples:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb
    - Rakefile
    - lib/tasks/**/*.rb
    - config/**/*.rb

Naming/RescuedExceptionsVariableName:
  PreferredName: error

Lint/MissingSuper:
  Exclude:
    - 'app/services/**/*'
