default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: scholare_development

test:
  <<: *default
  database: scholare_test

production:
  <<: *default
  database: scholare_production
  username: scholare
  password: <%= ENV["SCHOLARE_DATABASE_PASSWORD"] %>
