default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV["PGHOST"] || "localhost" %>

development:
  <<: *default
  database: scholare_development

test:
  <<: *default
  database: scholare_test
  database: <%= ENV['DB_NAME_PREFIX'] || 'scholare_test' %><%= ENV['TEST_ENV_NUMBER'] %>

production:
  <<: *default
  database: scholare_production
  username: scholare
  password: <%= ENV["SCHOLARE_DATABASE_PASSWORD"] %>
