name: ci
on: push

jobs:
  ci:
    timeout-minutes: 15
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14-alpine
        ports: ['5432:5432']
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password

        options:
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - run: sudo apt-get install -y libsndfile-dev

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'

      - name: Install bundler dependencies
        run: bundle install

      - name: Install npm dependencies
        run: npm install

      - name: Run rubocop
        run: bundle exec rubocop

      - name: Build database and run tests
        env:
          DATABASE_URL: postgres://postgres:password@localhost:5432/postgres
          PG_DATABASE: postgres
          PG_HOST: localhost
          PG_USER: postgres
          PG_PASSWORD: password
          RAILS_ENV: test
          COVERAGE: 1
          CI: 1

        run: |
          bin/rails db:schema:load
          bundle exec rspec

      - name: Upload simplecov results
        if: ${{ failure() }}
        uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: coverage/

      - name: Upload capybara artifacts
        if: ${{ failure() }}
        uses: actions/upload-artifact@v3
        with:
          name: capybara
          path: tmp/capybara
